### ISSUE TITLE
com.google.android.setupwizard

### ISSUE THREAD

**Issue by Vihru** [dogiex/MIUI-XML-10-FINNISH#10]
## Perustiedot
Laite: mi8 dipper
MIUI versio: Weekly 9.1.24

Change font size englanniksi.
![screenshot_2019-01-29-18-15-06-978_com google android setupwizard](https://user-images.githubusercontent.com/16348370/51923861-8319a880-23f4-11e9-9ed5-85a8cef5621f.png)

**Comment by dogiex** [comment]
@Vihru Missä tämä asetus on?
En löydä noita kyseisiä käännöksiä nimittäin mistään.

**Comment by dogiex** [comment]
Näyttäisi siis olevan setupwizard, mutta sellaista apk-tiedostoa ei ole käännettäväksi EU-rommissa.
Pitääpi tutkia.

**Comment by Vihru** [comment]
@dogiex, kun asentaa rommin niin alkuvaiheessa se kysyy tuollaisia..

**Comment by dogiex** [comment]
Vieläkö tämä ongelma on ajankohtainen?
Itselläni ei nimittäin ongelman mukaista määritystä ollut Mi 9 laitteessa.

**Comment by Vihru** [comment]
Tämä on minun mielestä jo korjaantunu..
