### ISSUE TITLE
com android setting -> ambient display ja muuta

### ISSUE THREAD

**Issue by Vihru** [dogiex/MIUI-XML-10-FINNISH#2]
## Perustiedot
Laite: Mi8
MIUI versio: Weekly 8.11.1

## Kuvaus
Katsotko merkityt kohdat, osa englanniksi.
ambient display sekä  show icons for incoming notifications
sekä notification style...

## Kuvakaappaus

![screenshot_2018-11-07-18-21-25-472_com android setting
![screenshot_2018-11-07-18-21-11-265_com android settings](https://user-images.githubusercontent.com/16348370/48144823-3e311a80-e2ba-11e8-96f4-616b50494036.png)
s](https://user-images.githubusercontent.com/16348370/48144809-370a0c80-e2ba-11e8-837d-5b36684fe16a.png)
![screenshot_2018-11-07-18-21-11-265_com android settings](https://user-images.githubusercontent.com/16348370/48144914-64ef5100-e2ba-11e8-886c-97a09f5e907c.png)

**Comment by dogiex** [comment]
Joo fixaan nuo ja muut ilmoitetut asiat mahdollisimman pian. Olen ollut tämän syksyn hyvin kiireinen muiden projektien kanssa, mutta taas parin viikon päästä projektit on loppu ja pääsen taas kääntämään kunnolla. Edellisestä päivityksestä onkin jo aikaa 😂
