### ISSUE TITLE
com.google.android.packageinstaller

### ISSUE THREAD

**Issue by Vihru** [dogiex/MIUI-XML-10-FINNISH#3]
## Perustiedot
Laite: Mi8 (dipper)
MIUI versio: Weekly 8.11.8

## Kuvaus
sovellukset kun kysyy lupia ni tekstit on enkuks.

## Kuvakaappaus
![screenshot_2018-11-10-20-14-53-853_com google android packageinstaller](https://user-images.githubusercontent.com/16348370/48304652-adf70d80-e525-11e8-86a1-37a3704b5790.png)

**Comment by dogiex** [comment]
Korjataan seuraavaksi 😉

**Comment by dogiex** [comment]
Onko kaikki ilmoitukset enkuksi vai vain tuo? Taitaa olla joska Mi 8 käyttää jo android 9?

**Comment by Vihru** [comment]
siis kaikki oikeuksia kyselevät ilmotukset enkuks.. varmaa tosta samasta sovelluspaketista löytyy ne muutki käännettävät..

**Comment by dogiex** [comment]
Juuh android 9 ne on vielä enkuksi, kun en ole niitä vielä sinne lisännyt. Ensi viikolla taas rupeaa olemaan aikaa, kun parit muut projektit tehtynä.

**Comment by dogiex** [comment]
Nyt pitäisi olla korjattu nuo :)

**Comment by Vihru** [comment]
vielä ei ainakaan 10.2 stablessa ole käännettynä

**Comment by dogiex** [comment]
Seuraavassa päivityksessä pitäisi sitten olla. Ei ilmeisesti kerennyt siihen päivitykseen.
